"""empty message

Revision ID: 336e253e0d60
Revises: 785c6f7059d3
Create Date: 2021-05-23 14:09:26.751311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336e253e0d60'
down_revision = '785c6f7059d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint('Venue_address_key', 'Venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Venue_address_key', 'Venue', ['address'])
    op.alter_column('Venue', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
