"""empty message

Revision ID: 4556ed9a81cb
Revises: 336e253e0d60
Create Date: 2021-05-23 21:57:41.959483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4556ed9a81cb'
down_revision = '336e253e0d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=True ) )
    op.drop_constraint('shows_pkey' , 'shows' , type_='primary')
    op.execute('UPDATE shows SET id = 1 WHERE id IS NULL')
    op.alter_column('shows' , 'id', nullable = False)
    op.create_primary_key('shows_pkey', 'shows', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'id')
    op.create_primary_key('shows_pkey', 'shows', ['venue_id','artist_id'])
    # ### end Alembic commands ###
