"""empty message

Revision ID: 785c6f7059d3
Revises: fb4c75bb2acb
Create Date: 2021-05-21 00:53:56.579778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785c6f7059d3'
down_revision = 'fb4c75bb2acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    op.drop_column('Artist', 'past_shows')
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Venue', 'past_shows')
    op.drop_column('Venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('upcoming_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('past_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('past_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('shows')
    # ### end Alembic commands ###
